mutation createUsuario(
  $nombre: String!
  $telefono: String!
  $email: String!
  $contrasena: String! 
  $fechanac: String!
  ) {
  createUsuario(
    input: { 
      nombre:$nombre
      telefono:$telefono
      correo:$email
      contrasena:$contrasena
      fechaNacimiento:$fechanac
  }) {
    usuario {
      id
      nombre
    }
  }
}