mutation createUsuario(
  $nombre: String!
  $telefono: String!
  $email: String!
  $contrasena: String! 
  $fechanac: String!
  ) {
  createUsuario(
    input: { 
      name:$nombre
      telephone:$telefono
      email:$email
      password:$contrasena
      fechaNacimiento:$fechanac
  }) {
    usuario {
      id
      name
    }
  }
}